# Generated by Django 5.2.11 on 2026-03-23 20:03

import email_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        max_length=255,
                        validators=[email_templates.models.validate_template_syntax],
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="If not set, default mail will be used.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "plain_message",
                    models.TextField(
                        blank=True,
                        default="Hi {{ user }}, Maktabiya, A Desk Booking App!",
                        help_text="If template field is set, this message will be ignored",
                        null=True,
                        verbose_name="Plain text content",
                    ),
                ),
                (
                    "html_template",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Custom template to use for the email. (Paths relative to             `settings.TEMPLATES[i]['DIRS']`)",
                        max_length=100,
                        null=True,
                        validators=[email_templates.models.validate_template_syntax],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
    ]
