# Generated by Django 5.2.11 on 2026-03-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Office Name")),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookings_per_day", models.PositiveIntegerField(default=0)),
                ("bookings_per_user_per_week", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Room Name")),
                (
                    "no_of_desk",
                    models.SmallIntegerField(default=0, verbose_name="Number of Desks"),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="app_core.office",
                        verbose_name="Office Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Desk Name")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="app_core.room",
                        verbose_name="Room Name",
                    ),
                ),
            ],
            options={
                "ordering": ["-room__name"],
            },
        ),
    ]
