# Generated by Django 5.2.11 on 2026-03-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("booked_on", models.DateField()),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_desk",
                        to="app_core.desk",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_office",
                        to="app_core.office",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_room",
                        to="app_core.room",
                    ),
                ),
            ],
        ),
    ]
